version: '3.8'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    networks:
      - app-network

  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://flask-app:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


