version: '3.8'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000" # Flask backend
    volumes:
      - ./uploads:/app/uploads # Persist uploads directory
    env_file:
      - .env # Load environment variables for Flask app

  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # React frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000 # Flask backend URL

