
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    networks:
      - app-network

  vue-app:
    build:
      context: ./front_end/front-end-app
    ports:
      - "3000:3000"
    environment:
      - VUE_APP_API_URL=http://flask-app:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


